server:
  error:
    include-message: always

spring:

  jpa:
    hibernate:
      ddl-auto: none

  data:
    mongodb:
      host: localhost
      port: 27017
      database: Tenants
      username: mongouser
      password: password

  flyway:
    locations: classpath:/dev/db/migration
    enabled: false

tenants:
  configurations:
    DevTenant:
      database-name: DevTenant
      url: jdbc:mysql://localhost:3306/
      username: admin
      password: password